/// Flutter icons Custom
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Custom
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';

  static const IconData xingCircleFilled = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData linkedinCircleFilled = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData linkedinSquareFilled = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData githubCircleFilled = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData mediumCircleFilled = IconData(0xe805, fontFamily: _kFontFam);
}
